theme: jekyll-theme-slate
title: This is a personal website belonging to Jesus Giovanni, an MJSP student of Hokudai.
description: Some snippets of information, and maybe links, are going to go here.
plugins:
  - jemoji
url: "https://jesusgio99.github.io/"
markdown: kramdown